spring:
  application:
    name: tasks
  datasource:
    url: jdbc:mysql://localhost:3306/hexagonal?serverTimezone=UTC
    username: root
    password: hexagonal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true # Initializes mySQL Schema structure
    hibernate:
      dll-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


